image: node:20

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - cp README.md ../
    - echo "@blum-unstoppable/blumsdk:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm run build && npm publish